project: "esn-research"
seeds: [2024, 706, 4410, 5385, 1029, 1219, 8380, 8931, 5963, 19800]
num_of_classes: 3

data: 
    type: "complement"

model: 
    name: "esn"
    Nu: 256
    Nx: 200
    Ny: 3
    density: 0.5
    input_scale: 0.01
    rho: 0.9

        optimizer: "tikhonov"